### ISSUE TITLE
Build Tool Error - PostProcessing 

### ISSUE THREAD

**Issue by tinnystudios** [LiminalVR/LiminalSdk-UnityPackage#12]

**Comment by MichaelLiminal** [comment]
Having experimented using the latest version of Unity's post-processing package (2.1.7), I've confirmed that you can create a limapp with post-processing and that an app can load said limapp so long as it has the post-processing package. The problem is that post-processing doesn't work with single pass rendering in 2018.3 (in my case, one eye renders without any post-processing, and the other is white).

Further investigation revealed this comment on Unity's GitHub page for V2 of the post-processing stack: https://github.com/Unity-Technologies/PostProcessing/issues/468#issuecomment-457881535

Unless we can change the stereo rendering mode, I'm not sure where we can go with this as the ball seems to be in Unity's court.
