### ISSUE TITLE
Serialization: Dynamic Unity Events

### ISSUE THREAD

**Issue by tinnystudios** [LiminalVR/LiminalSdk-UnityPackage#8]
Normal Unity Events work fine however a dynamic one does not fire events.

**Comment by MichaelLiminal** [comment]
At some point between when the Liminal SDK was first made into a package and now, this issue was apparently resolved. It is **not** working in the liminal lab (which uses the old variant) but is working in the SDK. As such, tomorrow I'd like to test it on a fresh unity scene as I want to confirm that it's the SDK that's fixed and not things simply weren't interfering with it.
